// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "config/ProfileDataEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "config/ProfileData.h"
#include "utils/EnumNaming.h"

namespace d2bs::config {

std::string EnumName(ProfileType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ProfileType::Invalid), .name = "Invalid"},
        {.bits = utils::EnumBits(ProfileType::SinglePlayer), .name = "SinglePlayer"},
        {.bits = utils::EnumBits(ProfileType::BattleNet), .name = "BattleNet"},
        {.bits = utils::EnumBits(ProfileType::OpenBattleNet), .name = "OpenBattleNet"},
        {.bits = utils::EnumBits(ProfileType::TcpIpHost), .name = "TcpIpHost"},
        {.bits = utils::EnumBits(ProfileType::TcpIpJoin), .name = "TcpIpJoin"},
    });
    return utils::NameEnumValue("ProfileType", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(ProfileType value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::config
