// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "components/script/ScriptEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "components/script/Script.h"
#include "utils/EnumNaming.h"

namespace d2bs {

std::string EnumName(StackCaptureMode value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(StackCaptureMode::Off), .name = "Off"},
        {.bits = ::d2bs::utils::EnumBits(StackCaptureMode::OnYield), .name = "OnYield"},
        {.bits = ::d2bs::utils::EnumBits(StackCaptureMode::OnEveryCall), .name = "OnEveryCall"},
    });
    return ::d2bs::utils::NameEnumValue("StackCaptureMode", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(StackCaptureMode value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs
