// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "components/script/ScriptTypesEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "components/script/ScriptTypes.h"
#include "utils/EnumNaming.h"

namespace d2bs {

std::string EnumName(ScriptState value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Starting), .name = "Starting"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Ready), .name = "Ready"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Running), .name = "Running"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Paused), .name = "Paused"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Stopping), .name = "Stopping"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Stopped), .name = "Stopped"},
    });
    return ::d2bs::utils::NameEnumValue("ScriptState", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ScriptMode value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(ScriptMode::InGame), .name = "InGame"},
        {.bits = ::d2bs::utils::EnumBits(ScriptMode::OutOfGame), .name = "OutOfGame"},
        {.bits = ::d2bs::utils::EnumBits(ScriptMode::Console), .name = "Console"},
    });
    return ::d2bs::utils::NameEnumValue("ScriptMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(DrawableHandler value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(DrawableHandler::Click), .name = "Click"},
        {.bits = ::d2bs::utils::EnumBits(DrawableHandler::Hover), .name = "Hover"},
    });
    return ::d2bs::utils::NameEnumValue("DrawableHandler", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(ScriptState value) {
    return EnumName(value);
}

std::string format_as(ScriptMode value) {
    return EnumName(value);
}

std::string format_as(DrawableHandler value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs
