// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "characterstate/UnitJsonEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "characterstate/UnitJson.h"
#include "utils/EnumNaming.h"

namespace d2bs::services::characterstate {

std::string EnumName(Detail value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Detail::Structural), .name = "Structural"},
        {.bits = utils::EnumBits(Detail::Full), .name = "Full"},
    });
    return utils::NameEnumValue("Detail", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(Detail value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::services::characterstate
