// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#pragma once

#include <cstdint>
#include <string>

#include "utils/EnumNaming.h"

namespace d2bs::game::console {

enum class ColorCode : char;
enum class MessageSource : uint8_t;
enum class MessageLevel : uint8_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(ColorCode value);
[[nodiscard]] std::string EnumName(MessageSource value);
[[nodiscard]] std::string EnumName(MessageLevel value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(ColorCode value);
[[nodiscard]] std::string format_as(MessageSource value);
[[nodiscard]] std::string format_as(MessageLevel value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::game::console
