// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "game/ConsoleEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "game/Console.h"
#include "utils/EnumNaming.h"

namespace d2bs::game::console {

std::string EnumName(ColorCode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ColorCode::White), .name = "White"},
        {.bits = utils::EnumBits(ColorCode::Red), .name = "Red"},
        {.bits = utils::EnumBits(ColorCode::NeonGreen), .name = "NeonGreen"},
        {.bits = utils::EnumBits(ColorCode::Blue), .name = "Blue"},
        {.bits = utils::EnumBits(ColorCode::DarkGold), .name = "DarkGold"},
        {.bits = utils::EnumBits(ColorCode::Grey), .name = "Grey"},
        {.bits = utils::EnumBits(ColorCode::Black), .name = "Black"},
        {.bits = utils::EnumBits(ColorCode::LightGold), .name = "LightGold"},
        {.bits = utils::EnumBits(ColorCode::Orange), .name = "Orange"},
        {.bits = utils::EnumBits(ColorCode::Yellow), .name = "Yellow"},
        {.bits = utils::EnumBits(ColorCode::DarkGreen), .name = "DarkGreen"},
        {.bits = utils::EnumBits(ColorCode::Purple), .name = "Purple"},
        {.bits = utils::EnumBits(ColorCode::Green), .name = "Green"},
    });
    return utils::NameEnumValue("ColorCode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(MessageSource value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(MessageSource::Print), .name = "Print"},
        {.bits = utils::EnumBits(MessageSource::ConsolePrint), .name = "ConsolePrint"},
        {.bits = utils::EnumBits(MessageSource::EvaluateResult), .name = "EvaluateResult"},
        {.bits = utils::EnumBits(MessageSource::Log), .name = "Log"},
    });
    return utils::NameEnumValue("MessageSource", ENTRIES, std::to_underlying(value));
}

std::string EnumName(MessageLevel value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(MessageLevel::Trace), .name = "Trace"},
        {.bits = utils::EnumBits(MessageLevel::Debug), .name = "Debug"},
        {.bits = utils::EnumBits(MessageLevel::Info), .name = "Info"},
        {.bits = utils::EnumBits(MessageLevel::Warn), .name = "Warn"},
        {.bits = utils::EnumBits(MessageLevel::Error), .name = "Error"},
        {.bits = utils::EnumBits(MessageLevel::Critical), .name = "Critical"},
    });
    return utils::NameEnumValue("MessageLevel", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(ColorCode value) {
    return EnumName(value);
}

std::string format_as(MessageSource value) {
    return EnumName(value);
}

std::string format_as(MessageLevel value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::game::console
