// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "game/ConstantsEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "game/Constants.h"
#include "utils/EnumNaming.h"

namespace d2bs::game {

std::string EnumName(CharFlag value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(CharFlag::Hardcore), .name = "Hardcore"},
        {.bits = utils::EnumBits(CharFlag::Expansion), .name = "Expansion"},
        {.bits = utils::EnumBits(CharFlag::Ladder), .name = "Ladder"},
    });
    return utils::NameEnumValue("CharFlag", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(CharFlag value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::game
