// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "game/MenuEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "game/Menu.h"
#include "utils/EnumNaming.h"

namespace d2bs::game {

std::string EnumName(OutOfGameLocation value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(OutOfGameLocation::PreSplash), .name = "PreSplash"},
        {.bits = utils::EnumBits(OutOfGameLocation::Lobby), .name = "Lobby"},
        {.bits = utils::EnumBits(OutOfGameLocation::WaitingInLine), .name = "WaitingInLine"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyChat), .name = "LobbyChat"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyCreateGame), .name = "LobbyCreateGame"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyJoinGame), .name = "LobbyJoinGame"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyLadder), .name = "LobbyLadder"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyChannel), .name = "LobbyChannel"},
        {.bits = utils::EnumBits(OutOfGameLocation::MainMenu), .name = "MainMenu"},
        {.bits = utils::EnumBits(OutOfGameLocation::Login), .name = "Login"},
        {.bits = utils::EnumBits(OutOfGameLocation::LoginError), .name = "LoginError"},
        {.bits = utils::EnumBits(OutOfGameLocation::UnableToConnect), .name = "UnableToConnect"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelect), .name = "CharacterSelect"},
        {.bits = utils::EnumBits(OutOfGameLocation::RealmDown), .name = "RealmDown"},
        {.bits = utils::EnumBits(OutOfGameLocation::Disconnected), .name = "Disconnected"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterCreateClassSelected),
         .name = "CharacterCreateClassSelected"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelectPleaseWait), .name = "CharacterSelectPleaseWait"},
        {.bits = utils::EnumBits(OutOfGameLocation::LostConnection), .name = "LostConnection"},
        {.bits = utils::EnumBits(OutOfGameLocation::SplashScreen), .name = "SplashScreen"},
        {.bits = utils::EnumBits(OutOfGameLocation::CDKeyInUse), .name = "CDKeyInUse"},
        {.bits = utils::EnumBits(OutOfGameLocation::SelectDifficultySinglePlayer),
         .name = "SelectDifficultySinglePlayer"},
        {.bits = utils::EnumBits(OutOfGameLocation::MainMenuConnecting), .name = "MainMenuConnecting"},
        {.bits = utils::EnumBits(OutOfGameLocation::InvalidCDKey), .name = "InvalidCDKey"},
        {.bits = utils::EnumBits(OutOfGameLocation::Connecting), .name = "Connecting"},
        {.bits = utils::EnumBits(OutOfGameLocation::ServerDown), .name = "ServerDown"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyPleaseWait), .name = "LobbyPleaseWait"},
        {.bits = utils::EnumBits(OutOfGameLocation::GameAlreadyExists), .name = "GameAlreadyExists"},
        {.bits = utils::EnumBits(OutOfGameLocation::Gateway), .name = "Gateway"},
        {.bits = utils::EnumBits(OutOfGameLocation::GameDoesNotExist), .name = "GameDoesNotExist"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterCreate), .name = "CharacterCreate"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterCreateAlreadyExists),
         .name = "CharacterCreateAlreadyExists"},
        {.bits = utils::EnumBits(OutOfGameLocation::AgreeToTerms), .name = "AgreeToTerms"},
        {.bits = utils::EnumBits(OutOfGameLocation::NewAccount), .name = "NewAccount"},
        {.bits = utils::EnumBits(OutOfGameLocation::PleaseRead), .name = "PleaseRead"},
        {.bits = utils::EnumBits(OutOfGameLocation::RegisterEmail), .name = "RegisterEmail"},
        {.bits = utils::EnumBits(OutOfGameLocation::Credits), .name = "Credits"},
        {.bits = utils::EnumBits(OutOfGameLocation::Cinematics), .name = "Cinematics"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterChangeRealm), .name = "CharacterChangeRealm"},
        {.bits = utils::EnumBits(OutOfGameLocation::GameIsFull), .name = "GameIsFull"},
        {.bits = utils::EnumBits(OutOfGameLocation::OtherMultiplayer), .name = "OtherMultiplayer"},
        {.bits = utils::EnumBits(OutOfGameLocation::TcpIp), .name = "TcpIp"},
        {.bits = utils::EnumBits(OutOfGameLocation::EnterIpAddress), .name = "EnterIpAddress"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelectNoChars), .name = "CharacterSelectNoChars"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelectChangeRealm), .name = "CharacterSelectChangeRealm"},
        {.bits = utils::EnumBits(OutOfGameLocation::UnableToConnectTcpIp), .name = "UnableToConnectTcpIp"},
    });
    return utils::NameEnumValue("OutOfGameLocation", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(OutOfGameLocation value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::game
