// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#pragma once

#include <cstdint>
#include <string>

#include "utils/EnumNaming.h"

namespace d2bs::game {

enum class ClickButton : uint8_t;
enum class Hand : uint8_t;
enum class KeyState : uint8_t;
enum class InventoryOwner : uint8_t;
enum class ClickResult : uint8_t;
enum class ControlType : uint32_t;
enum class PartyMode : uint32_t;
enum class CancelMode : int32_t;
enum class GoldActionMode : int32_t;
enum class TradeInfoMode : uint32_t;
enum class AcceptTradeQueryMode : uint32_t;
enum class ShopMode : int32_t;
enum class ItemCostMode : int32_t;
enum class CharacterClass : uint32_t;
enum class Difficulty : uint32_t;
enum class GameState : uint32_t;
enum class IpcMode : uint32_t;
enum class LoginStatus : uint8_t;
enum class UnitType : uint32_t;
enum class UnitKind : uint32_t;
enum class NodePage : uint8_t;
enum class ItemLocation : uint8_t;
enum class StashTabKind : uint8_t;
enum class StashTabType : uint8_t;
enum class ItemQuality : uint32_t;
enum class BodyLocation : uint8_t;
enum class MonsterSpecType : uint32_t;
enum class GameType : uint32_t;
enum class ScreenSize : uint32_t;
enum class WeaponSet : uint32_t;
enum class MoveMode : uint32_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(ClickButton value);
[[nodiscard]] std::string EnumName(Hand value);
[[nodiscard]] std::string EnumName(KeyState value);
[[nodiscard]] std::string EnumName(InventoryOwner value);
[[nodiscard]] std::string EnumName(ClickResult value);
[[nodiscard]] std::string EnumName(ControlType value);
[[nodiscard]] std::string EnumName(PartyMode value);
[[nodiscard]] std::string EnumName(CancelMode value);
[[nodiscard]] std::string EnumName(GoldActionMode value);
[[nodiscard]] std::string EnumName(TradeInfoMode value);
[[nodiscard]] std::string EnumName(AcceptTradeQueryMode value);
[[nodiscard]] std::string EnumName(ShopMode value);
[[nodiscard]] std::string EnumName(ItemCostMode value);
[[nodiscard]] std::string EnumName(CharacterClass value);
[[nodiscard]] std::string EnumName(Difficulty value);
[[nodiscard]] std::string EnumName(GameState value);
[[nodiscard]] std::string EnumName(IpcMode value);
[[nodiscard]] std::string EnumName(LoginStatus value);
[[nodiscard]] std::string EnumName(UnitType value);
[[nodiscard]] std::string EnumName(UnitKind value);
[[nodiscard]] std::string EnumName(NodePage value);
[[nodiscard]] std::string EnumName(ItemLocation value);
[[nodiscard]] std::string EnumName(StashTabKind value);
[[nodiscard]] std::string EnumName(StashTabType value);
[[nodiscard]] std::string EnumName(ItemQuality value);
[[nodiscard]] std::string EnumName(BodyLocation value);
[[nodiscard]] std::string EnumName(MonsterSpecType value);
[[nodiscard]] std::string EnumName(GameType value);
[[nodiscard]] std::string EnumName(ScreenSize value);
[[nodiscard]] std::string EnumName(WeaponSet value);
[[nodiscard]] std::string EnumName(MoveMode value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(ClickButton value);
[[nodiscard]] std::string format_as(Hand value);
[[nodiscard]] std::string format_as(KeyState value);
[[nodiscard]] std::string format_as(InventoryOwner value);
[[nodiscard]] std::string format_as(ClickResult value);
[[nodiscard]] std::string format_as(ControlType value);
[[nodiscard]] std::string format_as(PartyMode value);
[[nodiscard]] std::string format_as(CancelMode value);
[[nodiscard]] std::string format_as(GoldActionMode value);
[[nodiscard]] std::string format_as(TradeInfoMode value);
[[nodiscard]] std::string format_as(AcceptTradeQueryMode value);
[[nodiscard]] std::string format_as(ShopMode value);
[[nodiscard]] std::string format_as(ItemCostMode value);
[[nodiscard]] std::string format_as(CharacterClass value);
[[nodiscard]] std::string format_as(Difficulty value);
[[nodiscard]] std::string format_as(GameState value);
[[nodiscard]] std::string format_as(IpcMode value);
[[nodiscard]] std::string format_as(LoginStatus value);
[[nodiscard]] std::string format_as(UnitType value);
[[nodiscard]] std::string format_as(UnitKind value);
[[nodiscard]] std::string format_as(NodePage value);
[[nodiscard]] std::string format_as(ItemLocation value);
[[nodiscard]] std::string format_as(StashTabKind value);
[[nodiscard]] std::string format_as(StashTabType value);
[[nodiscard]] std::string format_as(ItemQuality value);
[[nodiscard]] std::string format_as(BodyLocation value);
[[nodiscard]] std::string format_as(MonsterSpecType value);
[[nodiscard]] std::string format_as(GameType value);
[[nodiscard]] std::string format_as(ScreenSize value);
[[nodiscard]] std::string format_as(WeaponSet value);
[[nodiscard]] std::string format_as(MoveMode value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::game
