// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#pragma once

#include <cstddef>
#include <string>

#include "utils/EnumNaming.h"

namespace d2bs::runtime::gameloop {

enum class FramePhase : size_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(FramePhase value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(FramePhase value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::gameloop
