// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "components/gameloop/GameLoopEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "components/gameloop/GameLoop.h"
#include "utils/EnumNaming.h"

namespace d2bs::runtime::gameloop {

std::string EnumName(FramePhase value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(FramePhase::Game), .name = "Game"},
        {.bits = utils::EnumBits(FramePhase::Asleep), .name = "Asleep"},
        {.bits = utils::EnumBits(FramePhase::Body), .name = "Body"},
        {.bits = utils::EnumBits(FramePhase::Drain), .name = "Drain"},
        {.bits = utils::EnumBits(FramePhase::AcquireWait), .name = "AcquireWait"},
        {.bits = utils::EnumBits(FramePhase::Draw), .name = "Draw"},
        {.bits = utils::EnumBits(FramePhase::Events), .name = "Events"},
        {.bits = utils::EnumBits(FramePhase::ScriptWait), .name = "ScriptWait"},
        {.bits = utils::EnumBits(FramePhase::CharacterState), .name = "CharacterState"},
    });
    return utils::NameEnumValue("FramePhase", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(FramePhase value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::gameloop
