// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "api/globals/ConstantsEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "api/globals/Constants.h"
#include "utils/EnumNaming.h"

namespace d2bs::api::globals {

std::string EnumName(FileMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(FileMode::Read), .name = "Read"},
        {.bits = utils::EnumBits(FileMode::Write), .name = "Write"},
        {.bits = utils::EnumBits(FileMode::Append), .name = "Append"},
    });
    return utils::NameEnumValue("FileMode", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(FileMode value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::api::globals
