// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "ContractEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "config/ProfileData.h"
#include "game/Console.h"
#include "game/Constants.h"
#include "game/Menu.h"
#include "game/Types.h"
#include "utils/EnumNaming.h"

namespace d2bs::config {

std::string EnumName(ProfileType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ProfileType::Invalid), .name = "Invalid"},
        {.bits = utils::EnumBits(ProfileType::SinglePlayer), .name = "SinglePlayer"},
        {.bits = utils::EnumBits(ProfileType::BattleNet), .name = "BattleNet"},
        {.bits = utils::EnumBits(ProfileType::OpenBattleNet), .name = "OpenBattleNet"},
        {.bits = utils::EnumBits(ProfileType::TcpIpHost), .name = "TcpIpHost"},
        {.bits = utils::EnumBits(ProfileType::TcpIpJoin), .name = "TcpIpJoin"},
    });
    return utils::NameEnumValue("ProfileType", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(ProfileType value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::config

namespace d2bs::game::console {

std::string EnumName(ColorCode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ColorCode::White), .name = "White"},
        {.bits = utils::EnumBits(ColorCode::Red), .name = "Red"},
        {.bits = utils::EnumBits(ColorCode::NeonGreen), .name = "NeonGreen"},
        {.bits = utils::EnumBits(ColorCode::Blue), .name = "Blue"},
        {.bits = utils::EnumBits(ColorCode::DarkGold), .name = "DarkGold"},
        {.bits = utils::EnumBits(ColorCode::Grey), .name = "Grey"},
        {.bits = utils::EnumBits(ColorCode::Black), .name = "Black"},
        {.bits = utils::EnumBits(ColorCode::LightGold), .name = "LightGold"},
        {.bits = utils::EnumBits(ColorCode::Orange), .name = "Orange"},
        {.bits = utils::EnumBits(ColorCode::Yellow), .name = "Yellow"},
        {.bits = utils::EnumBits(ColorCode::DarkGreen), .name = "DarkGreen"},
        {.bits = utils::EnumBits(ColorCode::Purple), .name = "Purple"},
        {.bits = utils::EnumBits(ColorCode::Green), .name = "Green"},
    });
    return utils::NameEnumValue("ColorCode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(MessageSource value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(MessageSource::Print), .name = "Print"},
        {.bits = utils::EnumBits(MessageSource::ConsolePrint), .name = "ConsolePrint"},
        {.bits = utils::EnumBits(MessageSource::EvaluateResult), .name = "EvaluateResult"},
        {.bits = utils::EnumBits(MessageSource::Log), .name = "Log"},
    });
    return utils::NameEnumValue("MessageSource", ENTRIES, std::to_underlying(value));
}

std::string EnumName(MessageLevel value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(MessageLevel::Trace), .name = "Trace"},
        {.bits = utils::EnumBits(MessageLevel::Debug), .name = "Debug"},
        {.bits = utils::EnumBits(MessageLevel::Info), .name = "Info"},
        {.bits = utils::EnumBits(MessageLevel::Warn), .name = "Warn"},
        {.bits = utils::EnumBits(MessageLevel::Error), .name = "Error"},
        {.bits = utils::EnumBits(MessageLevel::Critical), .name = "Critical"},
    });
    return utils::NameEnumValue("MessageLevel", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(ColorCode value) {
    return EnumName(value);
}

std::string format_as(MessageSource value) {
    return EnumName(value);
}

std::string format_as(MessageLevel value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::game::console

namespace d2bs::game {

std::string EnumName(CharFlag value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(CharFlag::Hardcore), .name = "Hardcore"},
        {.bits = utils::EnumBits(CharFlag::Expansion), .name = "Expansion"},
        {.bits = utils::EnumBits(CharFlag::Ladder), .name = "Ladder"},
    });
    return utils::NameEnumValue("CharFlag", ENTRIES, std::to_underlying(value));
}

std::string EnumName(OutOfGameLocation value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(OutOfGameLocation::PreSplash), .name = "PreSplash"},
        {.bits = utils::EnumBits(OutOfGameLocation::Lobby), .name = "Lobby"},
        {.bits = utils::EnumBits(OutOfGameLocation::WaitingInLine), .name = "WaitingInLine"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyChat), .name = "LobbyChat"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyCreateGame), .name = "LobbyCreateGame"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyJoinGame), .name = "LobbyJoinGame"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyLadder), .name = "LobbyLadder"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyChannel), .name = "LobbyChannel"},
        {.bits = utils::EnumBits(OutOfGameLocation::MainMenu), .name = "MainMenu"},
        {.bits = utils::EnumBits(OutOfGameLocation::Login), .name = "Login"},
        {.bits = utils::EnumBits(OutOfGameLocation::LoginError), .name = "LoginError"},
        {.bits = utils::EnumBits(OutOfGameLocation::UnableToConnect), .name = "UnableToConnect"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelect), .name = "CharacterSelect"},
        {.bits = utils::EnumBits(OutOfGameLocation::RealmDown), .name = "RealmDown"},
        {.bits = utils::EnumBits(OutOfGameLocation::Disconnected), .name = "Disconnected"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterCreateClassSelected),
         .name = "CharacterCreateClassSelected"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelectPleaseWait), .name = "CharacterSelectPleaseWait"},
        {.bits = utils::EnumBits(OutOfGameLocation::LostConnection), .name = "LostConnection"},
        {.bits = utils::EnumBits(OutOfGameLocation::SplashScreen), .name = "SplashScreen"},
        {.bits = utils::EnumBits(OutOfGameLocation::CDKeyInUse), .name = "CDKeyInUse"},
        {.bits = utils::EnumBits(OutOfGameLocation::SelectDifficultySinglePlayer),
         .name = "SelectDifficultySinglePlayer"},
        {.bits = utils::EnumBits(OutOfGameLocation::MainMenuConnecting), .name = "MainMenuConnecting"},
        {.bits = utils::EnumBits(OutOfGameLocation::InvalidCDKey), .name = "InvalidCDKey"},
        {.bits = utils::EnumBits(OutOfGameLocation::Connecting), .name = "Connecting"},
        {.bits = utils::EnumBits(OutOfGameLocation::ServerDown), .name = "ServerDown"},
        {.bits = utils::EnumBits(OutOfGameLocation::LobbyPleaseWait), .name = "LobbyPleaseWait"},
        {.bits = utils::EnumBits(OutOfGameLocation::GameAlreadyExists), .name = "GameAlreadyExists"},
        {.bits = utils::EnumBits(OutOfGameLocation::Gateway), .name = "Gateway"},
        {.bits = utils::EnumBits(OutOfGameLocation::GameDoesNotExist), .name = "GameDoesNotExist"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterCreate), .name = "CharacterCreate"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterCreateAlreadyExists),
         .name = "CharacterCreateAlreadyExists"},
        {.bits = utils::EnumBits(OutOfGameLocation::AgreeToTerms), .name = "AgreeToTerms"},
        {.bits = utils::EnumBits(OutOfGameLocation::NewAccount), .name = "NewAccount"},
        {.bits = utils::EnumBits(OutOfGameLocation::PleaseRead), .name = "PleaseRead"},
        {.bits = utils::EnumBits(OutOfGameLocation::RegisterEmail), .name = "RegisterEmail"},
        {.bits = utils::EnumBits(OutOfGameLocation::Credits), .name = "Credits"},
        {.bits = utils::EnumBits(OutOfGameLocation::Cinematics), .name = "Cinematics"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterChangeRealm), .name = "CharacterChangeRealm"},
        {.bits = utils::EnumBits(OutOfGameLocation::GameIsFull), .name = "GameIsFull"},
        {.bits = utils::EnumBits(OutOfGameLocation::OtherMultiplayer), .name = "OtherMultiplayer"},
        {.bits = utils::EnumBits(OutOfGameLocation::TcpIp), .name = "TcpIp"},
        {.bits = utils::EnumBits(OutOfGameLocation::EnterIpAddress), .name = "EnterIpAddress"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelectNoChars), .name = "CharacterSelectNoChars"},
        {.bits = utils::EnumBits(OutOfGameLocation::CharacterSelectChangeRealm), .name = "CharacterSelectChangeRealm"},
        {.bits = utils::EnumBits(OutOfGameLocation::UnableToConnectTcpIp), .name = "UnableToConnectTcpIp"},
    });
    return utils::NameEnumValue("OutOfGameLocation", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ClickButton value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ClickButton::Left), .name = "Left"},
        {.bits = utils::EnumBits(ClickButton::Right), .name = "Right"},
        {.bits = utils::EnumBits(ClickButton::ShiftLeft), .name = "ShiftLeft"},
        {.bits = utils::EnumBits(ClickButton::ShiftRight), .name = "ShiftRight"},
        {.bits = utils::EnumBits(ClickButton::Mercenary), .name = "Mercenary"},
    });
    return utils::NameEnumValue("ClickButton", ENTRIES, std::to_underlying(value));
}

std::string EnumName(Hand value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Hand::Right), .name = "Right"},
        {.bits = utils::EnumBits(Hand::Left), .name = "Left"},
    });
    return utils::NameEnumValue("Hand", ENTRIES, std::to_underlying(value));
}

std::string EnumName(KeyState value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(KeyState::Down), .name = "Down"},
        {.bits = utils::EnumBits(KeyState::Up), .name = "Up"},
    });
    return utils::NameEnumValue("KeyState", ENTRIES, std::to_underlying(value));
}

std::string EnumName(InventoryOwner value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(InventoryOwner::Player), .name = "Player"},
        {.bits = utils::EnumBits(InventoryOwner::Mercenary), .name = "Mercenary"},
    });
    return utils::NameEnumValue("InventoryOwner", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ClickResult value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ClickResult::Dispatched), .name = "Dispatched"},
        {.bits = utils::EnumBits(ClickResult::TransactionInProgress), .name = "TransactionInProgress"},
        {.bits = utils::EnumBits(ClickResult::InvalidTarget), .name = "InvalidTarget"},
        {.bits = utils::EnumBits(ClickResult::NotAnItem), .name = "NotAnItem"},
        {.bits = utils::EnumBits(ClickResult::StashTabUnavailable), .name = "StashTabUnavailable"},
    });
    return utils::NameEnumValue("ClickResult", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ControlType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ControlType::Unknown), .name = "Unknown"},
        {.bits = utils::EnumBits(ControlType::EditBox), .name = "EditBox"},
        {.bits = utils::EnumBits(ControlType::Image), .name = "Image"},
        {.bits = utils::EnumBits(ControlType::Unused), .name = "Unused"},
        {.bits = utils::EnumBits(ControlType::TextBox), .name = "TextBox"},
        {.bits = utils::EnumBits(ControlType::ScrollBar), .name = "ScrollBar"},
        {.bits = utils::EnumBits(ControlType::Button), .name = "Button"},
        {.bits = utils::EnumBits(ControlType::List), .name = "List"},
    });
    return utils::NameEnumValue("ControlType", ENTRIES, std::to_underlying(value));
}

std::string EnumName(PartyMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(PartyMode::AllowLoot), .name = "AllowLoot"},
        {.bits = utils::EnumBits(PartyMode::Unhostile), .name = "Unhostile"},
        {.bits = utils::EnumBits(PartyMode::Invite), .name = "Invite"},
        {.bits = utils::EnumBits(PartyMode::Leave), .name = "Leave"},
        {.bits = utils::EnumBits(PartyMode::Hostile), .name = "Hostile"},
        {.bits = utils::EnumBits(PartyMode::HostileAlt), .name = "HostileAlt"},
    });
    return utils::NameEnumValue("PartyMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(CancelMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(CancelMode::CloseInteract), .name = "CloseInteract"},
        {.bits = utils::EnumBits(CancelMode::ClearCursor), .name = "ClearCursor"},
        {.bits = utils::EnumBits(CancelMode::CloseNPC), .name = "CloseNPC"},
        {.bits = utils::EnumBits(CancelMode::ClearScreen), .name = "ClearScreen"},
    });
    return utils::NameEnumValue("CancelMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(GoldActionMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(GoldActionMode::Drop), .name = "Drop"},
        {.bits = utils::EnumBits(GoldActionMode::Trade), .name = "Trade"},
        {.bits = utils::EnumBits(GoldActionMode::Deposit), .name = "Deposit"},
        {.bits = utils::EnumBits(GoldActionMode::Withdraw), .name = "Withdraw"},
    });
    return utils::NameEnumValue("GoldActionMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(TradeInfoMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(TradeInfoMode::RecentTradeId), .name = "RecentTradeId"},
        {.bits = utils::EnumBits(TradeInfoMode::RecentTradeName), .name = "RecentTradeName"},
        {.bits = utils::EnumBits(TradeInfoMode::RecentTradeId2), .name = "RecentTradeId2"},
    });
    return utils::NameEnumValue("TradeInfoMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(AcceptTradeQueryMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(AcceptTradeQueryMode::IsAccepted), .name = "IsAccepted"},
        {.bits = utils::EnumBits(AcceptTradeQueryMode::RecentTradeId), .name = "RecentTradeId"},
        {.bits = utils::EnumBits(AcceptTradeQueryMode::IsBlocked), .name = "IsBlocked"},
    });
    return utils::NameEnumValue("AcceptTradeQueryMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ShopMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ShopMode::Sell), .name = "Sell"},
        {.bits = utils::EnumBits(ShopMode::Buy), .name = "Buy"},
        {.bits = utils::EnumBits(ShopMode::BuyFill), .name = "BuyFill"},
    });
    return utils::NameEnumValue("ShopMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ItemCostMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ItemCostMode::Buy), .name = "Buy"},
        {.bits = utils::EnumBits(ItemCostMode::Sell), .name = "Sell"},
        {.bits = utils::EnumBits(ItemCostMode::Repair), .name = "Repair"},
    });
    return utils::NameEnumValue("ItemCostMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(CharacterClass value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(CharacterClass::Amazon), .name = "Amazon"},
        {.bits = utils::EnumBits(CharacterClass::Sorceress), .name = "Sorceress"},
        {.bits = utils::EnumBits(CharacterClass::Necromancer), .name = "Necromancer"},
        {.bits = utils::EnumBits(CharacterClass::Paladin), .name = "Paladin"},
        {.bits = utils::EnumBits(CharacterClass::Barbarian), .name = "Barbarian"},
        {.bits = utils::EnumBits(CharacterClass::Druid), .name = "Druid"},
        {.bits = utils::EnumBits(CharacterClass::Assassin), .name = "Assassin"},
    });
    return utils::NameEnumValue("CharacterClass", ENTRIES, std::to_underlying(value));
}

std::string EnumName(Difficulty value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Difficulty::Normal), .name = "Normal"},
        {.bits = utils::EnumBits(Difficulty::Nightmare), .name = "Nightmare"},
        {.bits = utils::EnumBits(Difficulty::Hell), .name = "Hell"},
        {.bits = utils::EnumBits(Difficulty::HighestAvailable), .name = "HighestAvailable"},
    });
    return utils::NameEnumValue("Difficulty", ENTRIES, std::to_underlying(value));
}

std::string EnumName(GameState value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(GameState::Null), .name = "Null"},
        {.bits = utils::EnumBits(GameState::Menu), .name = "Menu"},
        {.bits = utils::EnumBits(GameState::InGame), .name = "InGame"},
        {.bits = utils::EnumBits(GameState::Busy), .name = "Busy"},
    });
    return utils::NameEnumValue("GameState", ENTRIES, std::to_underlying(value));
}

std::string EnumName(IpcMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(IpcMode::Evaluate), .name = "Evaluate"},
        {.bits = utils::EnumBits(IpcMode::SwitchProfile), .name = "SwitchProfile"},
    });
    return utils::NameEnumValue("IpcMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(LoginStatus value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(LoginStatus::Success), .name = "Success"},
        {.bits = utils::EnumBits(LoginStatus::Timeout), .name = "Timeout"},
        {.bits = utils::EnumBits(LoginStatus::Error), .name = "Error"},
    });
    return utils::NameEnumValue("LoginStatus", ENTRIES, std::to_underlying(value));
}

std::string EnumName(UnitType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(UnitType::Player), .name = "Player"},
        {.bits = utils::EnumBits(UnitType::Monster), .name = "Monster"},
        {.bits = utils::EnumBits(UnitType::Object), .name = "Object"},
        {.bits = utils::EnumBits(UnitType::Missile), .name = "Missile"},
        {.bits = utils::EnumBits(UnitType::Item), .name = "Item"},
        {.bits = utils::EnumBits(UnitType::Tile), .name = "Tile"},
    });
    return utils::NameEnumValue("UnitType", ENTRIES, std::to_underlying(value));
}

std::string EnumName(UnitKind value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(UnitKind::Player), .name = "Player"},
        {.bits = utils::EnumBits(UnitKind::Regular), .name = "Regular"},
        {.bits = utils::EnumBits(UnitKind::InventoryItem), .name = "InventoryItem"},
    });
    return utils::NameEnumValue("UnitKind", ENTRIES, std::to_underlying(value));
}

std::string EnumName(NodePage value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(NodePage::Storage), .name = "Storage"},
        {.bits = utils::EnumBits(NodePage::Belt), .name = "Belt"},
        {.bits = utils::EnumBits(NodePage::Equipped), .name = "Equipped"},
    });
    return utils::NameEnumValue("NodePage", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ItemLocation value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ItemLocation::Ground), .name = "Ground"},
        {.bits = utils::EnumBits(ItemLocation::Equip), .name = "Equip"},
        {.bits = utils::EnumBits(ItemLocation::Belt), .name = "Belt"},
        {.bits = utils::EnumBits(ItemLocation::Inventory), .name = "Inventory"},
        {.bits = utils::EnumBits(ItemLocation::Store), .name = "Store"},
        {.bits = utils::EnumBits(ItemLocation::Trade), .name = "Trade"},
        {.bits = utils::EnumBits(ItemLocation::Cube), .name = "Cube"},
        {.bits = utils::EnumBits(ItemLocation::Stash), .name = "Stash"},
        {.bits = utils::EnumBits(ItemLocation::Null), .name = "Null"},
    });
    return utils::NameEnumValue("ItemLocation", ENTRIES, std::to_underlying(value));
}

std::string EnumName(StashTabKind value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(StashTabKind::Personal), .name = "Personal"},
        {.bits = utils::EnumBits(StashTabKind::Shared), .name = "Shared"},
    });
    return utils::NameEnumValue("StashTabKind", ENTRIES, std::to_underlying(value));
}

std::string EnumName(StashTabType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(StashTabType::Normal), .name = "Normal"},
        {.bits = utils::EnumBits(StashTabType::AdvancedStash), .name = "AdvancedStash"},
        {.bits = utils::EnumBits(StashTabType::Chronicle), .name = "Chronicle"},
    });
    return utils::NameEnumValue("StashTabType", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ItemQuality value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ItemQuality::Inferior), .name = "Inferior"},
        {.bits = utils::EnumBits(ItemQuality::Normal), .name = "Normal"},
        {.bits = utils::EnumBits(ItemQuality::Superior), .name = "Superior"},
        {.bits = utils::EnumBits(ItemQuality::Magic), .name = "Magic"},
        {.bits = utils::EnumBits(ItemQuality::Set), .name = "Set"},
        {.bits = utils::EnumBits(ItemQuality::Rare), .name = "Rare"},
        {.bits = utils::EnumBits(ItemQuality::Unique), .name = "Unique"},
        {.bits = utils::EnumBits(ItemQuality::Crafted), .name = "Crafted"},
        {.bits = utils::EnumBits(ItemQuality::Tempered), .name = "Tempered"},
    });
    return utils::NameEnumValue("ItemQuality", ENTRIES, std::to_underlying(value));
}

std::string EnumName(BodyLocation value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(BodyLocation::None), .name = "None"},
        {.bits = utils::EnumBits(BodyLocation::Head), .name = "Head"},
        {.bits = utils::EnumBits(BodyLocation::Amulet), .name = "Amulet"},
        {.bits = utils::EnumBits(BodyLocation::Body), .name = "Body"},
        {.bits = utils::EnumBits(BodyLocation::RightPrimary), .name = "RightPrimary"},
        {.bits = utils::EnumBits(BodyLocation::LeftPrimary), .name = "LeftPrimary"},
        {.bits = utils::EnumBits(BodyLocation::RightRing), .name = "RightRing"},
        {.bits = utils::EnumBits(BodyLocation::LeftRing), .name = "LeftRing"},
        {.bits = utils::EnumBits(BodyLocation::Belt), .name = "Belt"},
        {.bits = utils::EnumBits(BodyLocation::Feet), .name = "Feet"},
        {.bits = utils::EnumBits(BodyLocation::Gloves), .name = "Gloves"},
        {.bits = utils::EnumBits(BodyLocation::RightSecondary), .name = "RightSecondary"},
        {.bits = utils::EnumBits(BodyLocation::LeftSecondary), .name = "LeftSecondary"},
    });
    return utils::NameEnumValue("BodyLocation", ENTRIES, std::to_underlying(value));
}

std::string EnumName(MonsterSpecType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(MonsterSpecType::SuperUnique), .name = "SuperUnique"},
        {.bits = utils::EnumBits(MonsterSpecType::Champion), .name = "Champion"},
        {.bits = utils::EnumBits(MonsterSpecType::Unique), .name = "Unique"},
        {.bits = utils::EnumBits(MonsterSpecType::Minion), .name = "Minion"},
    });
    return utils::NameEnumValue("MonsterSpecType", ENTRIES, std::to_underlying(value));
}

std::string EnumName(GameType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(GameType::Classic), .name = "Classic"},
        {.bits = utils::EnumBits(GameType::Expansion), .name = "Expansion"},
    });
    return utils::NameEnumValue("GameType", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ScreenSize value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ScreenSize::Res640x480), .name = "Res640x480"},
        {.bits = utils::EnumBits(ScreenSize::Res800x600), .name = "Res800x600"},
    });
    return utils::NameEnumValue("ScreenSize", ENTRIES, std::to_underlying(value));
}

std::string EnumName(WeaponSet value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(WeaponSet::Primary), .name = "Primary"},
        {.bits = utils::EnumBits(WeaponSet::Secondary), .name = "Secondary"},
    });
    return utils::NameEnumValue("WeaponSet", ENTRIES, std::to_underlying(value));
}

std::string EnumName(MoveMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(MoveMode::Walk), .name = "Walk"},
        {.bits = utils::EnumBits(MoveMode::Run), .name = "Run"},
    });
    return utils::NameEnumValue("MoveMode", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(CharFlag value) {
    return EnumName(value);
}

std::string format_as(OutOfGameLocation value) {
    return EnumName(value);
}

std::string format_as(ClickButton value) {
    return EnumName(value);
}

std::string format_as(Hand value) {
    return EnumName(value);
}

std::string format_as(KeyState value) {
    return EnumName(value);
}

std::string format_as(InventoryOwner value) {
    return EnumName(value);
}

std::string format_as(ClickResult value) {
    return EnumName(value);
}

std::string format_as(ControlType value) {
    return EnumName(value);
}

std::string format_as(PartyMode value) {
    return EnumName(value);
}

std::string format_as(CancelMode value) {
    return EnumName(value);
}

std::string format_as(GoldActionMode value) {
    return EnumName(value);
}

std::string format_as(TradeInfoMode value) {
    return EnumName(value);
}

std::string format_as(AcceptTradeQueryMode value) {
    return EnumName(value);
}

std::string format_as(ShopMode value) {
    return EnumName(value);
}

std::string format_as(ItemCostMode value) {
    return EnumName(value);
}

std::string format_as(CharacterClass value) {
    return EnumName(value);
}

std::string format_as(Difficulty value) {
    return EnumName(value);
}

std::string format_as(GameState value) {
    return EnumName(value);
}

std::string format_as(IpcMode value) {
    return EnumName(value);
}

std::string format_as(LoginStatus value) {
    return EnumName(value);
}

std::string format_as(UnitType value) {
    return EnumName(value);
}

std::string format_as(UnitKind value) {
    return EnumName(value);
}

std::string format_as(NodePage value) {
    return EnumName(value);
}

std::string format_as(ItemLocation value) {
    return EnumName(value);
}

std::string format_as(StashTabKind value) {
    return EnumName(value);
}

std::string format_as(StashTabType value) {
    return EnumName(value);
}

std::string format_as(ItemQuality value) {
    return EnumName(value);
}

std::string format_as(BodyLocation value) {
    return EnumName(value);
}

std::string format_as(MonsterSpecType value) {
    return EnumName(value);
}

std::string format_as(GameType value) {
    return EnumName(value);
}

std::string format_as(ScreenSize value) {
    return EnumName(value);
}

std::string format_as(WeaponSet value) {
    return EnumName(value);
}

std::string format_as(MoveMode value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::game
