#pragma once

#include <cstdint>

namespace d2bs::script {

// A reference edge the wrapper needs so its owner stays reachable while it
// lives. Declared rather than built, because only the frontend can make one.
enum class KeepAlive : uint8_t {
    None,
    // Keep the receiver of the call that produced this wrapper alive.
    Receiver,
};

// Whether a constructor may be called without `new`.
enum class Construct : uint8_t { RequireNew, AllowPlainCall };

// Frees a native. Always generated by the typed layer, so it is only ever
// `delete static_cast<T*>(p)` - which is all a finalizer is allowed to be on an
// engine whose finalizers may not call back into it. A binding never writes one
// and so can never smuggle script work into a finalizer.
//
// Declared once, on the class, and read back off the class when a wrapper is
// collected. Nothing carries one alongside a native, so the two ends of an
// instance's life cannot be given different hooks.
using Destroy = void (*)(void* native);

// Identity of a bound class, process-wide and independent of any engine
// instance. The frontend resolves it to whatever per-isolate template or class
// it needs, inside the call - which is what lets a binding hand back an
// instance of another class without ever naming a template.
class ClassKey {
   public:
    ClassKey() = default;
    explicit ClassKey(void* record) : record_(record) {}

    [[nodiscard]] void* Record() const { return record_; }

   private:
    void* record_ = nullptr;
};

// A value this call made, sitting in the engine's own call frame: an object
// being built, an array being built, or a wrapper. All three are placed the
// same way, so a destination declares one overload for the three rather than
// three overloads for the one thing.
//
// Non-virtual, one pointer wide, and never held by pointer - it names what the
// three have in common, it is not an interface to them.
class Slot {
   public:
    [[nodiscard]] void* State() const { return state_; }

   protected:
    Slot() = default;
    explicit Slot(void* state) : state_(state) {}

   private:
    void* state_ = nullptr;
};

// A wrapper the call has made, waiting to be put somewhere.
//
// It is a slot in the engine's own call frame - the same storage a builder
// takes - so it roots nothing of its own and cannot outlive the call, which is
// the property that lets an engine with exact rooting implement it. Making one
// and placing it are separate steps, so the same handle reaches a return value,
// an array slot or an object key through those destinations' ordinary Set
// overloads: one call per way of owning a native rather than one per
// (ownership, destination) pair.
//
// Nodiscard because a wrapper nobody placed is a wrapper nothing refers to, and
// it takes its native with it when it is collected.
//
// Default-constructed when the engine refused to build the wrapper. Placing one
// of those stores nothing, so a binding never has to ask which it got.
class [[nodiscard]] Instance : public Slot {
   public:
    Instance() = default;
    explicit Instance(void* slot) : Slot(slot) {}

    // The native behind it, if it is an instance of that class - the same
    // question Value::Instance answers about an argument. Null for a wrapper of
    // another class, and for one the engine refused to build.
    [[nodiscard]] void* Native(ClassKey of) const;
};

}  // namespace d2bs::script
