// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "dde/DdeServiceEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "dde/DdeService.h"
#include "utils/EnumNaming.h"

namespace d2bs::services::dde {

std::string EnumName(Transaction value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Transaction::Request), .name = "Request"},
        {.bits = utils::EnumBits(Transaction::Poke), .name = "Poke"},
        {.bits = utils::EnumBits(Transaction::Evaluate), .name = "Evaluate"},
    });
    return utils::NameEnumValue("Transaction", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(Transaction value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::services::dde
