// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "RuntimeEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "api/globals/Constants.h"
#include "components/characterstate/UnitJson.h"
#include "components/dde/DdeService.h"
#include "components/drawing/Drawable.h"
#include "components/gameloop/GameLoop.h"
#include "components/navigation/ExitFinder.h"
#include "components/navigation/Pathfinder.h"
#include "components/script/Script.h"
#include "components/script/ScriptTypes.h"
#include "utils/EnumNaming.h"

namespace d2bs::api::globals {

std::string EnumName(FileMode value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(FileMode::Read), .name = "Read"},
        {.bits = utils::EnumBits(FileMode::Write), .name = "Write"},
        {.bits = utils::EnumBits(FileMode::Append), .name = "Append"},
    });
    return utils::NameEnumValue("FileMode", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(FileMode value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::api::globals

namespace d2bs::runtime::characterstate {

std::string EnumName(Detail value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Detail::Structural), .name = "Structural"},
        {.bits = utils::EnumBits(Detail::Full), .name = "Full"},
    });
    return utils::NameEnumValue("Detail", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(Detail value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::characterstate

namespace d2bs::runtime::dde {

std::string EnumName(Transaction value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Transaction::Request), .name = "Request"},
        {.bits = utils::EnumBits(Transaction::Poke), .name = "Poke"},
        {.bits = utils::EnumBits(Transaction::Evaluate), .name = "Evaluate"},
    });
    return utils::NameEnumValue("Transaction", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(Transaction value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::dde

namespace d2bs::runtime::drawing {

std::string EnumName(Align value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Align::Left), .name = "Left"},
        {.bits = utils::EnumBits(Align::Right), .name = "Right"},
        {.bits = utils::EnumBits(Align::Center), .name = "Center"},
    });
    return utils::NameEnumValue("Align", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(Align value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::drawing

namespace d2bs::runtime::gameloop {

std::string EnumName(FramePhase value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(FramePhase::Game), .name = "Game"},
        {.bits = utils::EnumBits(FramePhase::Asleep), .name = "Asleep"},
        {.bits = utils::EnumBits(FramePhase::Body), .name = "Body"},
        {.bits = utils::EnumBits(FramePhase::Drain), .name = "Drain"},
        {.bits = utils::EnumBits(FramePhase::AcquireWait), .name = "AcquireWait"},
        {.bits = utils::EnumBits(FramePhase::Draw), .name = "Draw"},
        {.bits = utils::EnumBits(FramePhase::Events), .name = "Events"},
        {.bits = utils::EnumBits(FramePhase::ScriptWait), .name = "ScriptWait"},
        {.bits = utils::EnumBits(FramePhase::CharacterState), .name = "CharacterState"},
    });
    return utils::NameEnumValue("FramePhase", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(FramePhase value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::gameloop

namespace d2bs::runtime::navigation {

std::string EnumName(ExitType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ExitType::Linkage), .name = "Linkage"},
        {.bits = utils::EnumBits(ExitType::Tile), .name = "Tile"},
    });
    return utils::NameEnumValue("ExitType", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ReductionType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ReductionType::Walk), .name = "Walk"},
        {.bits = utils::EnumBits(ReductionType::Teleport), .name = "Teleport"},
        {.bits = utils::EnumBits(ReductionType::None), .name = "None"},
        {.bits = utils::EnumBits(ReductionType::JSCallback), .name = "JSCallback"},
    });
    return utils::NameEnumValue("ReductionType", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(ExitType value) {
    return EnumName(value);
}

std::string format_as(ReductionType value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::navigation

namespace d2bs {

std::string EnumName(StackCaptureMode value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(StackCaptureMode::Off), .name = "Off"},
        {.bits = ::d2bs::utils::EnumBits(StackCaptureMode::OnYield), .name = "OnYield"},
        {.bits = ::d2bs::utils::EnumBits(StackCaptureMode::OnEveryCall), .name = "OnEveryCall"},
    });
    return ::d2bs::utils::NameEnumValue("StackCaptureMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ScriptState value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Starting), .name = "Starting"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Ready), .name = "Ready"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Running), .name = "Running"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Paused), .name = "Paused"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Stopping), .name = "Stopping"},
        {.bits = ::d2bs::utils::EnumBits(ScriptState::Stopped), .name = "Stopped"},
    });
    return ::d2bs::utils::NameEnumValue("ScriptState", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ScriptMode value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(ScriptMode::InGame), .name = "InGame"},
        {.bits = ::d2bs::utils::EnumBits(ScriptMode::OutOfGame), .name = "OutOfGame"},
        {.bits = ::d2bs::utils::EnumBits(ScriptMode::Console), .name = "Console"},
    });
    return ::d2bs::utils::NameEnumValue("ScriptMode", ENTRIES, std::to_underlying(value));
}

std::string EnumName(DrawableHandler value) {
    static constexpr auto ENTRIES = std::to_array<::d2bs::utils::EnumEntry>({
        {.bits = ::d2bs::utils::EnumBits(DrawableHandler::Click), .name = "Click"},
        {.bits = ::d2bs::utils::EnumBits(DrawableHandler::Hover), .name = "Hover"},
    });
    return ::d2bs::utils::NameEnumValue("DrawableHandler", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(StackCaptureMode value) {
    return EnumName(value);
}

std::string format_as(ScriptState value) {
    return EnumName(value);
}

std::string format_as(ScriptMode value) {
    return EnumName(value);
}

std::string format_as(DrawableHandler value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs
