// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

#include "utils/EnumNaming.h"

namespace d2bs::api::globals {

enum class FileMode : int32_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(FileMode value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(FileMode value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::api::globals

namespace d2bs::runtime::drawing {

enum class Align : uint8_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(Align value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(Align value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::drawing

namespace d2bs::runtime::gameloop {

enum class FramePhase : size_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(FramePhase value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(FramePhase value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::gameloop

namespace d2bs {

enum class StackCaptureMode : uint8_t;
enum class ScriptState : uint8_t;
enum class ScriptMode : uint8_t;
enum class DrawableHandler : uint8_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(StackCaptureMode value);
[[nodiscard]] std::string EnumName(ScriptState value);
[[nodiscard]] std::string EnumName(ScriptMode value);
[[nodiscard]] std::string EnumName(DrawableHandler value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(StackCaptureMode value);
[[nodiscard]] std::string format_as(ScriptState value);
[[nodiscard]] std::string format_as(ScriptMode value);
[[nodiscard]] std::string format_as(DrawableHandler value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs
