// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "utils/UtilsEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "utils/EnumNaming.h"
#include "utils/Profiling.h"

namespace d2bs::profiling {

std::string EnumName(NativeCall value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(NativeCall::Function), .name = "Function"},
        {.bits = utils::EnumBits(NativeCall::Getter), .name = "Getter"},
        {.bits = utils::EnumBits(NativeCall::Setter), .name = "Setter"},
    });
    return utils::NameEnumValue("NativeCall", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(NativeCall value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::profiling
