// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "components/drawing/DrawableEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "components/drawing/Drawable.h"
#include "utils/EnumNaming.h"

namespace d2bs::runtime::drawing {

std::string EnumName(Align value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(Align::Left), .name = "Left"},
        {.bits = utils::EnumBits(Align::Right), .name = "Right"},
        {.bits = utils::EnumBits(Align::Center), .name = "Center"},
    });
    return utils::NameEnumValue("Align", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(Align value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::runtime::drawing
