// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "CoreEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "detour/Hook.h"
#include "utils/EnumNaming.h"

namespace d2bs::detour {

std::string EnumName(AttachResult value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(AttachResult::Queued), .name = "Queued"},
        {.bits = utils::EnumBits(AttachResult::AlreadyAttached), .name = "AlreadyAttached"},
        {.bits = utils::EnumBits(AttachResult::DuplicateBody), .name = "DuplicateBody"},
        {.bits = utils::EnumBits(AttachResult::ModuleNotLoaded), .name = "ModuleNotLoaded"},
        {.bits = utils::EnumBits(AttachResult::TargetMissing), .name = "TargetMissing"},
        {.bits = utils::EnumBits(AttachResult::Failed), .name = "Failed"},
    });
    return utils::NameEnumValue("AttachResult", ENTRIES, std::to_underlying(value));
}

std::string EnumName(DetachResult value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(DetachResult::Queued), .name = "Queued"},
        {.bits = utils::EnumBits(DetachResult::NotAttached), .name = "NotAttached"},
        {.bits = utils::EnumBits(DetachResult::NotOpen), .name = "NotOpen"},
        {.bits = utils::EnumBits(DetachResult::Failed), .name = "Failed"},
    });
    return utils::NameEnumValue("DetachResult", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(AttachResult value) {
    return EnumName(value);
}

std::string format_as(DetachResult value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::detour
