"""Extract (tableIndex -> tableName) and (tableIndex, columnIndex -> columnName)
lookups from a local MPQStats stat-table definition (BaseStatTable[] / BinField[]
arrays) and emit a constexpr C++ header.

Runs with stdlib only. Idempotent: re-running produces byte-identical output.

Usage:
    python scripts/gen_txt_tables.py [--reference-dir reference/d2bs]
                                     [--output src/frontends/js/api/globals/TxtTables.h]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


# Matches one entry in MPQStats.cpp's BaseStatTable[]:
#   {0x8426F0, 0x8426EC, itemTable, "items", ARRAYSIZE(itemTable), 0xFFFF},
# Captures (var_name, table_name). The sentinel `{0}` has no quoted string and
# is naturally skipped.
_BASE_STAT_ENTRY_RE = re.compile(
    r"""\{
        \s* [^,{}]+ ,       # dwEntry (hex address)
        \s* [^,{}]+ ,       # dwMaxEntriesOffset
        \s* (\w+)    \s* ,  # pTable var name  (captured)
        \s* " ([^"]+) "     # szTableName       (captured)
    """,
    re.VERBOSE,
)

# Matches one column entry in a BinField array:
#   {"flippyfile", FIELDTYPE_DATA_ASCII, 0x1f, 0x0},
# Captures the column name. Sentinels like `{0}` or `{0,0,0,0}` are skipped.
_COLUMN_ENTRY_RE = re.compile(r'\{\s*"([^"]+)"\s*,')


def extract_tables(mpqstats_cpp: str) -> list[tuple[str, str]]:
    """Return [(columns_var_name, table_name), ...] in declaration order."""
    m = re.search(
        r"MPQTable\s+BaseStatTable\[\]\s*=\s*\{(.*?)\};",
        mpqstats_cpp,
        re.DOTALL,
    )
    if not m:
        raise RuntimeError("Could not locate BaseStatTable[] in MPQStats.cpp")
    return _BASE_STAT_ENTRY_RE.findall(m.group(1))


def extract_columns(mpqstats_h: str, var_name: str) -> list[str]:
    """Return column names for `static BinField <var_name>[] = { ... };`."""
    pattern = re.compile(
        rf"BinField\s+{re.escape(var_name)}\[\]\s*=\s*\{{(.*?)\}};",
        re.DOTALL,
    )
    m = pattern.search(mpqstats_h)
    if not m:
        raise RuntimeError(f"Could not locate BinField {var_name}[] in MPQStats.h")
    return _COLUMN_ENTRY_RE.findall(m.group(1))


def _sanitize_ident(name: str) -> str:
    """Map a table name to a valid C++ identifier suffix."""
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def emit_header(tables: list[tuple[str, list[str]]], script_rel: str) -> str:
    lines: list[str] = []
    emit = lines.append

    total_columns = sum(len(cols) for _, cols in tables)

    emit("// Auto-generated by " + script_rel + ". DO NOT EDIT.")
    emit("// Regenerate with: python " + script_rel)
    emit("//")
    emit("// Schema of the Diablo II 1.14d data tables (.txt): table index -> name,")
    emit("// and per-table column index -> name. Includes the appended 'affixes' table")
    emit("// (magicprefix / magicsuffix).")
    emit(f"// Summary: {len(tables)} tables, {total_columns} columns total.")
    emit("#pragma once")
    emit("")
    emit("#include <array>")
    emit("#include <span>")
    emit("#include <string_view>")
    emit("")
    emit("namespace d2bs::game {")
    emit("")

    # Widths for aligning trailing `// [idx] ...` comments.
    idx_width = len(str(len(tables) - 1))
    # Longest `"name",` (2 quotes + comma); used to pad entries for alignment.
    max_name_entry = max(len(name) + 3 for name, _ in tables)

    # --- Table name lookup: table index -> table name. ------------------------
    emit("// ============================================================================")
    emit("// Table name lookup: table index -> canonical .txt table name.")
    emit("// ============================================================================")
    emit(
        f"inline constexpr std::array<std::string_view, {len(tables)}> TXT_TABLE_NAMES = {{"
    )
    for idx, (name, _) in enumerate(tables):
        entry = f'"{name}",'
        emit(f"    {entry.ljust(max_name_entry)}  // [{idx:>{idx_width}}]")
    emit("};")
    emit("")

    # --- Per-table column-name arrays. ----------------------------------------
    for idx, (name, columns) in enumerate(tables):
        ident = _sanitize_ident(name).upper()
        emit("// ----------------------------------------------------------------------------")
        emit(f"// [{idx:>{idx_width}}] {name} - {len(columns)} columns")
        emit("// ----------------------------------------------------------------------------")
        emit(
            f"inline constexpr std::array<std::string_view, {len(columns)}> "
            f"TXT_COLUMNS_{ident} = {{"
        )
        col_idx_width = len(str(len(columns) - 1)) if columns else 1
        # Longest `"colname",` string for alignment of trailing index comment.
        max_col_entry = max(len(col) + 3 for col in columns)  # 3 = two quotes + comma
        for c_idx, col in enumerate(columns):
            entry = f'"{col}",'
            emit(f"    {entry.ljust(max_col_entry)}  // [{c_idx:>{col_idx_width}}]")
        emit("};")
        emit("")

    # --- Column lookup: table index -> span of column names. ------------------
    emit("// ============================================================================")
    emit("// Column lookup: table index -> span of that table's column names.")
    emit("// Use together with TXT_TABLE_NAMES to resolve (tableIdx, colIdx) -> names.")
    emit("// ============================================================================")
    emit(
        f"inline constexpr std::array<std::span<const std::string_view>, "
        f"{len(tables)}> TXT_COLUMNS_BY_TABLE = {{"
    )
    max_ident_len = max(len(_sanitize_ident(name)) for name, _ in tables)
    for idx, (name, _) in enumerate(tables):
        ident = _sanitize_ident(name).upper()
        span_expr = f"std::span<const std::string_view>{{TXT_COLUMNS_{ident}}},"
        # Pad the span expression so the trailing `// [idx] name` comment aligns.
        # The identifier width term ensures all closing `}},` line up.
        padded = span_expr.ljust(len("std::span<const std::string_view>{TXT_COLUMNS_") + max_ident_len + 2)
        emit(f"    {padded}  // [{idx:>{idx_width}}] {name}")
    emit("};")
    emit("")

    emit("}  // namespace d2bs::game")
    emit("")

    return "\n".join(lines)


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reference-dir",
        default=str(repo_root / "reference" / "d2bs"),
        help="Directory containing MPQStats.cpp and MPQStats.h",
    )
    parser.add_argument(
        "--output",
        default=str(repo_root / "src" / "frontends" / "js" / "api" / "globals" / "TxtTables.h"),
        help="Output header path",
    )
    args = parser.parse_args()

    ref_dir = Path(args.reference_dir)
    mpqstats_cpp = (ref_dir / "MPQStats.cpp").read_text(encoding="utf-8")
    mpqstats_h = (ref_dir / "MPQStats.h").read_text(encoding="utf-8")

    entries = extract_tables(mpqstats_cpp)
    if not entries:
        raise RuntimeError("BaseStatTable[] parsed to zero entries")

    tables: list[tuple[str, list[str]]] = []
    for var_name, table_name in entries:
        columns = extract_columns(mpqstats_h, var_name)
        if not columns:
            raise RuntimeError(f"{var_name} parsed to zero columns")
        tables.append((table_name, columns))

    # The magic-affix table (magicprefix.txt / magicsuffix.txt share one in-memory
    # D2MagicAffixTxt array, indexed by affix id) is not in the reference's
    # BaseStatTable, so append it here. Column order matches magicprefix.txt.
    tables.append(
        (
            "affixes",
            [
                "Name", "version", "spawnable", "rare", "level", "maxlevel",
                "levelreq", "classspecific", "class", "classlevelreq", "frequency",
                "group", "mod1code", "mod1param", "mod1min", "mod1max", "mod2code",
                "mod2param", "mod2min", "mod2max", "mod3code", "mod3param", "mod3min",
                "mod3max", "transform", "transformcolor", "itype1", "itype2",
                "itype3", "itype4", "itype5", "itype6", "itype7", "etype1", "etype2",
                "etype3", "etype4", "etype5", "divide", "multiply", "add",
            ],
        )
    )

    # properties.txt is likewise absent from the reference BaseStatTable; d2bsng's
    # runtime reader sources it from Game.exe (TXT_AllocTxt_properties). Columns are
    # listed in struct/offset order - wProp ('code'), then the nSet, wVal, nFunc,
    # wStat arrays in turn - matching COLS_PROPERTIES in MPQStats.cpp.
    tables.append(
        (
            "properties",
            [
                "code",
                "set1", "set2", "set3", "set4", "set5", "set6", "set7",
                "val1", "val2", "val3", "val4", "val5", "val6", "val7",
                "func1", "func2", "func3", "func4", "func5", "func6", "func7",
                "stat1", "stat2", "stat3", "stat4", "stat5", "stat6", "stat7",
            ],
        )
    )

    # Reference-path of the script as displayed in the header banner (forward slashes).
    script_rel = (
        Path(__file__).resolve().relative_to(repo_root).as_posix()
    )

    out_text = emit_header(tables, script_rel)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # Force LF: the header is committed with Unix line endings, and Path.write_text
    # would otherwise emit CRLF on Windows, turning every regen into a whole-file diff.
    output_path.write_text(out_text, encoding="utf-8", newline="\n")

    total_columns = sum(len(cols) for _, cols in tables)
    print(
        f"Wrote {output_path} "
        f"({len(tables)} tables, {total_columns} columns)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
