#!/usr/bin/env python3
"""Generate the EnumName / format_as overloads for every namespace-scope enumeration.

Finds the headers of every project under src/ (each .vcxproj) that define an
enumeration at namespace scope, parses them with libclang (with that project's
own include directories), and writes one checked-in pair per project, at the
project's root and named after it (contract -> ContractEnumNames.h / .cpp):

  <Project>EnumNames.h    forward-declares all the project's enumerations and
                          declares, in each enumeration's own namespace,
                          EnumName(value) and format_as(value) (fmt's hook);
                          includes utils/EnumNaming.h for the std::formatter.
                          Every header that defines one of the enumerations
                          includes it, so an enumeration cannot be used without
                          its names - and, being only declarations, it is cheap.
  <Project>EnumNames.cpp  a name table per enumeration and the definitions.

It also keeps the wiring in step: each such header gets the #include of its
project's companion, and the .vcxproj lists the pair. A header that stops
defining an enumeration loses the include, and a project that has none left
loses the pair. Rerun after adding or changing an enumeration; --check reports
stale output or wiring instead of writing it (non-zero exit), for CI.
.gitattributes marks the pairs linguist-generated, so GitHub collapses them in
diffs.

    pip install libclang
    python scripts/gen_enum_names.py [--check]

An enumeration nested in a class or function, or declared in a .cpp, gets no
overloads. A covered enumeration must be forward-declarable: scoped, or unscoped
with a fixed underlying type, which must be a builtin or standard integer type.
The output goes through clang-format (from the Visual Studio install, else
PATH), so it passes build.ps1 check-format as written.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

try:
    from clang.cindex import CursorKind, Index, TokenKind, TranslationUnit
except ImportError:
    sys.exit("Required: pip install libclang")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_api import find_system_includes, v8_include_dir  # noqa: E402 - after the sys.path tweak

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"

# Projects whose headers the code spells with the project directory's own name
# ("utils/Strings.h"); every other project's headers are spelled relative to the
# project directory ("game/Types.h" in contract).
SPELLED_FROM_PARENT = {SRC / "utils", SRC / "navigation"}
# Directories never scanned: build output, and vendored code that keeps its own style.
SKIP_DIRS = {"Release", "Debug", "x64", "Win32", "vcpkg_installed"}
VENDORED = []  # e.g. SRC / "some" / "third_party" - paths under src/ to leave alone
SUFFIX = "EnumNames"
SHARED_HEADER = "utils/EnumNaming.h"
STD_INTS = {f"{s}int{n}_t" for s in ("", "u") for n in (8, 16, 32, 64)}
BUILTIN_TYPE_WORDS = {"char", "short", "int", "long", "signed", "unsigned", "bool", "wchar_t", "char8_t",
                      "char16_t", "char32_t"}

ENUM_DEF_RE = re.compile(r"\benum\s+(?:class\s+|struct\s+)?\w+\s*(?::[^;{]*)?\{")
GENERATED = "// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration."
INCLUDE_COMMENT = "// ReSharper disable once CppUnusedIncludeDirective - EnumName / format_as for the enumerations below"


class Project:
    def __init__(self, vcxproj):
        self.vcxproj = vcxproj
        self.dir = vcxproj.parent
        self.spelling_root = self.dir.parent if self.dir in SPELLED_FROM_PARENT else self.dir
        self.include_dirs = self._include_dirs()

    def _include_dirs(self):
        text = self.vcxproj.read_text(encoding="utf-8-sig")
        found = []
        for value in re.findall(r"<AdditionalIncludeDirectories>(.*?)</AdditionalIncludeDirectories>", text):
            for item in value.split(";"):
                item = (item.replace("$(ProjectDir)", str(self.dir) + "\\")
                        .replace("$(SolutionDir)", str(REPO_ROOT) + "\\")
                        .replace("$(MSBuildThisFileDirectory)", str(self.dir) + "\\"))
                if "$(" in item or "%(" in item or not item.strip():
                    continue
                path = Path(item.strip())
                if path.exists() and path not in found:
                    found.append(path)
        return found

    def spell(self, path):
        return path.relative_to(self.spelling_root).as_posix()

    def item(self, path):
        """*path* as the .vcxproj lists it."""
        return str(path.relative_to(self.dir)).replace("/", "\\")


def is_generated(path):
    with path.open(encoding="utf-8", errors="replace") as f:
        return f.readline().rstrip("\n") == GENERATED


def companion(project, extension):
    """The project's generated file: at its root, named after it (contract.vcxproj -> ContractEnumNames.h)."""
    stem = project.vcxproj.stem
    return project.dir / f"{stem[:1].upper()}{stem[1:]}{SUFFIX}{extension}"


def project_files(project, projects, pattern):
    """The files matching *pattern* that belong to *project*: not build output, not vendored, not in a nested project."""
    for path in sorted(project.dir.rglob(pattern)):
        if SKIP_DIRS & set(path.relative_to(project.dir).parts[:-1]):
            continue
        if any(path.is_relative_to(v) for v in VENDORED):
            continue
        if any(other.dir != project.dir and other.dir.is_relative_to(project.dir) and path.is_relative_to(other.dir)
               for other in projects):
            continue
        yield path


def written_underlying_type(cursor):
    """The underlying type as the declaration spells it (`enum X : T {` -> "T"), or None when it has none.

    Spelled as written rather than canonicalised: size_t is `unsigned int` on Win32 and
    `unsigned long long` on x64, so the forward declaration must say size_t too."""
    tokens, after_colon = [], False
    for token in cursor.get_tokens():
        if token.kind == TokenKind.PUNCTUATION and token.spelling == "{":
            break
        if after_colon:
            tokens.append(token.spelling)
        elif token.kind == TokenKind.PUNCTUATION and token.spelling == ":":
            after_colon = True
    return " ".join(tokens).replace(" :: ", "::") if after_colon else None


def type_header(spelling):
    """The standard header a forward declaration needs for *spelling*; raises for a non-standard type."""
    bare = spelling.removeprefix("std::")
    if bare in STD_INTS:
        return "<cstdint>"
    if bare in ("size_t", "ptrdiff_t"):
        return "<cstddef>"
    if set(spelling.split()) <= BUILTIN_TYPE_WORDS:
        return None
    raise RuntimeError(f"underlying type '{spelling}' is not a builtin or standard integer type")


def parse_project(project, headers):
    """{header path: [enumeration records]} for the namespace-scope enumerations of *headers*."""
    source = "".join(f'#include "{project.spell(h)}"\n' for h in headers)
    args = ["-x", "c++", "-std=c++23", "-fms-compatibility", "-fms-extensions", "-DWIN32", "-DNOMINMAX",
            "-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH",  # the pip libclang may predate the STL's minimum
            "-ferror-limit=0", "-w"]
    for inc in [project.spelling_root, *project.include_dirs]:
        args += ["-I", str(inc)]
    extra = [v8_include_dir()] + sorted((REPO_ROOT / "vcpkg_installed").glob("*/*/include"))
    for inc in [*extra, *find_system_includes()]:
        if inc and Path(inc).exists():
            args += ["-isystem", str(inc)]
    tu = Index.create().parse("enum_names_probe.cpp", args=args, unsaved_files=[("enum_names_probe.cpp", source)],
                              options=TranslationUnit.PARSE_SKIP_FUNCTION_BODIES)
    fatal = [str(d) for d in tu.diagnostics if d.severity >= 4]  # a failed include, not an unevaluable check
    if fatal:
        raise RuntimeError(f"libclang could not parse {project.vcxproj.name}'s headers:\n  " + "\n  ".join(fatal))

    wanted = {h.resolve(): h for h in headers}
    found = {h: [] for h in headers}
    seen = set()
    for cursor in tu.cursor.walk_preorder():
        if cursor.kind != CursorKind.ENUM_DECL or not cursor.is_definition() or not cursor.spelling:
            continue
        header = wanted.get(Path(cursor.location.file.name).resolve()) if cursor.location.file else None
        if header is None or cursor.is_anonymous():
            continue
        scopes, parent = [], cursor.semantic_parent
        while parent is not None and parent.kind != CursorKind.TRANSLATION_UNIT:
            if parent.kind != CursorKind.NAMESPACE or not parent.spelling:
                break  # nested in a class / function, or in an anonymous namespace
            scopes.insert(0, parent.spelling)
            parent = parent.semantic_parent
        else:
            enumerators = [c.spelling for c in cursor.get_children() if c.kind == CursorKind.ENUM_CONSTANT_DECL]
            qualified = "::".join(scopes + [cursor.spelling])
            if not enumerators or not scopes or qualified in seen:
                continue
            seen.add(qualified)
            scoped, underlying = cursor.is_scoped_enum(), written_underlying_type(cursor)
            if not scoped and underlying is None:
                raise RuntimeError(f"{project.spell(header)}: {qualified} cannot be forward-declared - "
                                   "give it a fixed underlying type (enum X : int32_t)")
            try:
                include = type_header(underlying) if underlying else None
            except RuntimeError as err:
                raise RuntimeError(f"{project.spell(header)}: {qualified}: {err}") from None
            found[header].append({"name": cursor.spelling, "namespace": "::".join(scopes),
                                  "enumerators": enumerators, "scoped": scoped, "underlying": underlying,
                                  "include": include})
    return {h: e for h, e in found.items() if e}


# --- Rendering ----------------------------------------------------------------


def by_namespace(enums):
    namespaces = {}
    for e in enums:
        namespaces.setdefault(e["namespace"], []).append(e)
    return namespaces


def utils_prefix(namespace):
    """How code in *namespace* names d2bs::utils."""
    if namespace == "d2bs::utils":
        return ""
    return "utils::" if namespace.startswith("d2bs::") else "::d2bs::utils::"


def forward_declaration(e):
    keyword = "enum class" if e["scoped"] else "enum"
    return f"{keyword} {e['name']}" + (f" : {e['underlying']};" if e["underlying"] else ";")


def render_header(enums):
    lines = [GENERATED, "", "#pragma once", ""]
    lines += [f"#include {h}" for h in sorted({e["include"] for e in enums if e["include"]} | {"<string>"})]
    lines += ["", f'#include "{SHARED_HEADER}"']
    for namespace, members in by_namespace(enums).items():
        lines += ["", f"namespace {namespace} {{", ""]
        lines += [forward_declaration(e) for e in members]
        lines += [
            "",
            "// A human-readable name for an enum value: the enumerator that has it (the first declared one",
            '// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",',
            '// else "Type(value)". std::format and fmt / spdlog print the same.',
        ]
        lines += [f"[[nodiscard]] std::string EnumName({e['name']} value);" for e in members]
        lines += ["", "// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name"]
        lines += [f"[[nodiscard]] std::string format_as({e['name']} value);" for e in members]
        lines += ["// NOLINTEND(readability-identifier-naming)", "", f"}}  // namespace {namespace}"]
    lines.append("")
    return "\n".join(lines)


def render_source(project, headers, enums):
    includes = sorted({f'#include "{project.spell(h)}"' for h in headers} | {f'#include "{SHARED_HEADER}"'})
    lines = [GENERATED, "", f'#include "{project.spell(companion(project, ".h"))}"', "",
             "#include <array>", "#include <string>", "#include <utility>", "", *includes]
    for namespace, members in by_namespace(enums).items():
        u = utils_prefix(namespace)
        lines += ["", f"namespace {namespace} {{"]
        for e in members:
            lines += [
                "",
                f"std::string EnumName({e['name']} value) {{",
                f"    static constexpr auto ENTRIES = std::to_array<{u}EnumEntry>({{",
                *(f'        {{.bits = {u}EnumBits({e["name"]}::{n}), .name = "{n}"}},' for n in e["enumerators"]),
                "    });",
                f'    return {u}NameEnumValue("{e["name"]}", ENTRIES, std::to_underlying(value));',
                "}",
            ]
        lines += ["", "// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name"]
        for e in members:
            lines += ["", f"std::string format_as({e['name']} value) {{", "    return EnumName(value);", "}"]
        lines += ["", "// NOLINTEND(readability-identifier-naming)", "", f"}}  // namespace {namespace}"]
    lines.append("")
    return "\n".join(lines)


# --- Wiring -------------------------------------------------------------------


def decode(raw):
    """(text with \\n line endings, the file's own newline, whether it had a byte-order mark)."""
    text = raw.decode("utf-8-sig")
    return text.replace("\r\n", "\n"), ("\r\n" if "\r\n" in text else "\n"), raw.startswith(b"\xef\xbb\xbf")


def encode(text, newline, bom):
    return (b"\xef\xbb\xbf" if bom else b"") + text.replace("\n", newline).encode("utf-8")


def wire_header(raw, include, wanted):
    """A header's bytes with the companion include added (after its last #include, else #pragma once)
    when *wanted*, or removed (with its comment) when not."""
    text, newline, bom = decode(raw)
    lines = text.split("\n")
    line = f'#include "{include}"'
    if line in lines:
        if wanted:
            return raw
        i = lines.index(line)
        start = i - 1 if i > 0 and lines[i - 1] == INCLUDE_COMMENT else i
        del lines[start:i + 1]
        if 0 < start < len(lines) and lines[start] == "" and lines[start - 1] == "":
            del lines[start]
        return encode("\n".join(lines), newline, bom)
    if not wanted:
        return raw
    anchor = max((i for i, l in enumerate(lines) if l.startswith("#include")), default=None)
    insert = [INCLUDE_COMMENT, line]
    if anchor is None:
        anchor = next(i for i, l in enumerate(lines) if l.startswith("#pragma once"))
        insert.insert(0, "")
    elif lines[anchor].startswith("#include <"):
        insert.insert(0, "")  # its own block after the system includes, as project includes are
    return encode("\n".join(lines[:anchor + 1] + insert + lines[anchor + 1:]), newline, bom)


def wire_project(project, add, remove):
    """The .vcxproj's bytes with each (kind, item) in *add* listed - alphabetically in the group holding
    that kind - and each item in *remove* dropped."""
    text, newline, bom = decode(project.vcxproj.read_bytes())
    for item in remove:
        text = re.sub(rf'^[ \t]*<Cl(?:Compile|Include) Include="{re.escape(item)}" />\n', "", text, flags=re.M)
    for kind, item in add:
        if f'<{kind} Include="{item}"' in text:
            continue
        existing = list(re.finditer(rf'^([ \t]*)<{kind} Include="([^"]*)"', text, re.M))
        if not existing:
            raise RuntimeError(f"{project.vcxproj.name}: no <{kind}> item group to add {item} to")
        entry = f'{existing[0].group(1)}<{kind} Include="{item}" />\n'
        after = next((m for m in existing if m.group(2).lower() > item.lower()), None)
        if after is None:
            last = existing[-1]
            end = text.index("\n", last.start()) + 1
            if not text[last.start():end].rstrip().endswith("/>"):  # an item with metadata
                end = text.index("\n", text.index(f"</{kind}>", last.start())) + 1
            text = text[:end] + entry + text[end:]
        else:
            text = text[:after.start()] + entry + text[after.start():]
    return encode(text, newline, bom)


# --- Driver -------------------------------------------------------------------


def find_clang_format():
    """The clang-format build.ps1 check-format would use: one on PATH at build.ps1's pinned
    version, else the Visual Studio one - so generated files pass the same check."""
    pinned = re.search(r"\$PINNED_CLANG_FORMAT\s*=\s*'([^']+)'", (REPO_ROOT / "build.ps1").read_text(encoding="utf-8"))
    if pinned:
        for directory in filter(None, os.environ.get("PATH", "").split(os.pathsep)):
            candidate = Path(directory) / "clang-format.exe"
            if candidate.exists():
                version = subprocess.run([str(candidate), "--version"], capture_output=True, text=True).stdout
                if pinned.group(1) in version:
                    return str(candidate)
    vswhere = Path(r"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe")
    if vswhere.exists():
        root = subprocess.run([str(vswhere), "-latest", "-products", "*", "-property", "installationPath"],
                              capture_output=True, text=True).stdout.strip()
        for sub in (r"VC\Tools\Llvm\x64\bin\clang-format.exe", r"VC\Tools\Llvm\bin\clang-format.exe"):
            if root and (Path(root) / sub).exists():
                return str(Path(root) / sub)
    return shutil.which("clang-format")


def clang_format(text, path, tool):
    """Formats *text* as if it were *path*, so the repository's .clang-format applies."""
    return subprocess.run([tool, f"--assume-filename={path}"], input=text, capture_output=True, text=True,
                          encoding="utf-8", check=True, cwd=REPO_ROOT).stdout


def plan(tool):
    """({path: new bytes}, [paths to delete], number of enumerations)."""
    projects = [Project(v) for v in sorted(SRC.rglob("*.vcxproj"))]
    writes, deletes, total = {}, [], 0
    for project in projects:
        generated = [p for pattern in (f"*{SUFFIX}.h", f"*{SUFFIX}.cpp")
                     for p in project_files(project, projects, pattern) if is_generated(p)]
        headers = [h for h in project_files(project, projects, "*.h")
                   if h not in generated and ENUM_DEF_RE.search(h.read_text(encoding="utf-8", errors="replace"))]
        parsed = parse_project(project, headers) if headers else {}

        enums = [e for es in parsed.values() for e in es]
        total += len(enums)

        header_path, source_path = companion(project, ".h"), companion(project, ".cpp")
        add, keep = [], set()
        if enums:
            writes[header_path] = clang_format(render_header(enums), header_path, tool).encode("utf-8")
            writes[source_path] = clang_format(render_source(project, parsed, enums), source_path,
                                               tool).encode("utf-8")
            keep = {header_path, source_path}
            add = [("ClCompile", project.item(source_path)), ("ClInclude", project.item(header_path))]

        # Generated files this run did not produce (a project with no enumerations left, or an
        # older layout) go, with their includes and .vcxproj items.
        stale = [p for p in generated if p not in keep]
        deletes += stale
        stale_includes = [project.spell(p) for p in stale if p.suffix == ".h"]
        for header in headers + [h for h in project_files(project, projects, "*.h")
                                 if h not in generated and h not in headers]:
            raw = original = header.read_bytes()
            for include in stale_includes:
                raw = wire_header(raw, include, wanted=False)
            raw = wire_header(raw, project.spell(header_path), wanted=header in parsed)
            if raw != original:
                writes[header] = raw
        if add or stale:
            writes[project.vcxproj] = wire_project(project, add, [project.item(p) for p in stale])
    return writes, deletes, total


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report stale output or wiring instead of writing it")
    args = parser.parse_args()

    tool = find_clang_format()
    if not tool:
        print("gen_enum_names: clang-format not found", file=sys.stderr)
        return 1
    try:
        writes, deletes, total = plan(tool)
    except RuntimeError as err:
        print(f"gen_enum_names: {err}", file=sys.stderr)
        return 1

    changed = []
    for path, content in writes.items():
        current = path.read_bytes() if path.exists() else None
        # Compared with line endings normalised; wiring keeps each file's own.
        if current is not None and current.replace(b"\r\n", b"\n") == content.replace(b"\r\n", b"\n"):
            continue
        changed.append(path)
        if not args.check:
            path.write_bytes(content)
    changed += deletes
    if not args.check:
        for path in deletes:
            path.unlink()
    rel = [p.relative_to(REPO_ROOT).as_posix() for p in changed]
    if args.check and rel:
        print("gen_enum_names: stale, rerun the script:\n  " + "\n  ".join(rel), file=sys.stderr)
        return 1
    print(f"{total} enumerations; " + (f"updated {len(rel)} files" if rel and not args.check else "up to date"))
    for path in rel if not args.check else []:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
