// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#include "navigation/NavigationEnumNames.h"

#include <array>
#include <string>
#include <utility>

#include "navigation/ExitFinder.h"
#include "navigation/Pathfinder.h"
#include "utils/EnumNaming.h"

namespace d2bs::navigation {

std::string EnumName(ExitType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ExitType::Linkage), .name = "Linkage"},
        {.bits = utils::EnumBits(ExitType::Tile), .name = "Tile"},
    });
    return utils::NameEnumValue("ExitType", ENTRIES, std::to_underlying(value));
}

std::string EnumName(ReductionType value) {
    static constexpr auto ENTRIES = std::to_array<utils::EnumEntry>({
        {.bits = utils::EnumBits(ReductionType::Walk), .name = "Walk"},
        {.bits = utils::EnumBits(ReductionType::Teleport), .name = "Teleport"},
        {.bits = utils::EnumBits(ReductionType::None), .name = "None"},
        {.bits = utils::EnumBits(ReductionType::JSCallback), .name = "JSCallback"},
    });
    return utils::NameEnumValue("ReductionType", ENTRIES, std::to_underlying(value));
}

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name

std::string format_as(ExitType value) {
    return EnumName(value);
}

std::string format_as(ReductionType value) {
    return EnumName(value);
}

// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::navigation
