// Generated by scripts/gen_enum_names.py - do not edit; rerun it after changing an enumeration.

#pragma once

#include <cstdint>
#include <string>

#include "utils/EnumNaming.h"

namespace d2bs::navigation {

enum class ExitType : uint32_t;
enum class ReductionType : int32_t;

// A human-readable name for an enum value: the enumerator that has it (the first declared one
// for aliases), else the single-bit enumerators that together make it up exactly as "A|B",
// else "Type(value)". std::format and fmt / spdlog print the same.
[[nodiscard]] std::string EnumName(ExitType value);
[[nodiscard]] std::string EnumName(ReductionType value);

// NOLINTBEGIN(readability-identifier-naming) - fmt's customisation point name
[[nodiscard]] std::string format_as(ExitType value);
[[nodiscard]] std::string format_as(ReductionType value);
// NOLINTEND(readability-identifier-naming)

}  // namespace d2bs::navigation
